### ISSUE TITLE
How to test NDP algo performance?

### ISSUE THREAD

**Issue by Wsky51** [NASA-NJU/Floodgate-NS3#1]
Hi 
May i ask how do you test NDP  algo performance in your paper Floodgate appendix? I could not find any NDP implementation in this repo.  
OR by using https://github.com/nets-cs-pub-ro/NDP/wiki/NDP-Simulator ? 

Thanks a lot.

**Comment by kathy-kxliu** [comment]
Hi,
This repo only includes the algorithm of Floodgate, along with DCQCN, TIMELY, and HPCC (which are provided by the open source code of HPCC). You may refer to the website you mentioned for the authors' implementation of NDP.
